services:
  database:
    container_name: mysql-db-primary
    hostname: mysql-db-primary
    build:
      context: ./platform/images/mysql
      dockerfile: MySQL.Dockerfile
    restart: on-failure
    ports:
      - 3306:3306
    command: --authentication_policy=mysql_native_password
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-db-primary:/var/lib/mysql
      - ./mysql-db-primary/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./platform/images/mysql/primary.conf.d/mysql.cnf:/etc/my.cnf
    networks:
      - rusty-network

  rusty:
    container_name: rusty
    build: .
    depends_on:
      - database
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3030:3030
    networks:
      - rusty-network
    command:
      - '/bin/sh'
      - '-c'
      - '/bin/sleep 10'

volumes:
  mysql-db-primary:
    driver: local

networks:
  rusty-network:
    driver: bridge
