# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  build-and-test:
    docker:
      - image: cimg/rust:1.82
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: rusty_test

    steps:
      - checkout
      
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y mysql-client
      
      - run:
          name: Wait for MySQL
          command: |
            for i in {1..30}; do
              if mysqladmin ping -h 127.0.0.1 -u root -ppassword --silent; then
                echo "MySQL is ready"
                break
              fi
              echo "Waiting for MySQL..."
              sleep 2
            done
      
      - run:
          name: Initialize database schema
          command: |
            mysql -h 127.0.0.1 -u root -ppassword rusty_test < platform/images/mysql/schema.sql
      
      - run:
          name: Seed test data
          command: |
            mysql -h 127.0.0.1 -u root -ppassword rusty_test -e "INSERT INTO users (id, name, email) VALUES (1, 'Test User', 'test@example.com');"
      
      - run:
          name: Check formatting
          command: cargo fmt -- --check
      
      - run:
          name: Run clippy
          command: cargo clippy -- -D warnings
      
      - run:
          name: Build
          command: cargo build --verbose
      
      - run:
          name: Run tests
          command: cargo test --verbose
          environment:
            DATABASE_URL: mysql://root:password@127.0.0.1:3306/rusty_test
            MYSQL_HOST: 127.0.0.1
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: rusty_test

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
